Update build-and-test3.yml

diff --git a/.github/workflows/build-and-test3.yml b/.github/workflows/build-and-test3.yml
--- a/.github/workflows/build-and-test3.yml
+++ b/.github/workflows/build-and-test3.yml
@@ -23,4 +23,12 @@ jobs:
         #    ./scripts/InstallChrome.sh
 
         - name: Test run
-          run: dotnet test UITestAutomation/UITestAutomation.csproj --configuration Release --no-build -- verbosity normal
+          run: dotnet test UITestAutomation/UITestAutomation.csproj --configuration Debug --no-build -- verbosity normal --logger trx
+
+        - name: Test Report
+          uses: dorny/test-reporter@v1
+          if: success() || failure()    # run this step even if previous step failed
+          with:
+            name: Test Results            # Name of the check run which will be created
+            path: reports/*.trx    # Path to test results
+            reporter: dotnet-trx        # Format of test results
